name: Build RedMi AC2100 (4.14)

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: v19.07.6

jobs:
  copy_config:
    name: Build Fireware
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - name: Invoke Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build OpenWrt
          token: '${{secrets.PERSONAL_TOKEN}}'
          inputs: '{"dir": "redmi.ac2100/4.14", "repo": "https://github.com/openwrt/openwrt", "branch": "${{github.event.inputs.version}}"}'
          
